### ISSUE TITLE
Error: IndexError: list index out of range

### ISSUE THREAD

**Issue by GrandGamerX** [BaraniARR/gogoanimeapi#3]
Hey there, first of all I'd like to say amazing initiative, I've so far not seen a single Gogoanime API. Now for the problem, I tried to make a simple script that prints all the download links for a given anime, here is the code:
```py
from gogoanimeapi import gogoanime as anime

for i in range(1,26):
    links = anime.get_episodes_link(animeid="shingeki-no-kyojin", episode_num=i)
    link = links['(HDP-mp4)']
    print(f'Episode {i}: {link}\n')
```
This works good up to episode 16 but then it spits out this error:
`Traceback (most recent call last):
  File "C:\Users\aashi\Desktop\DownloaderX.py", line 4, in <module>
    links = anime.get_episodes_link(animeid="shingeki-no-kyojin", episode_num=i)
  File "D:\Python\lib\site-packages\gogoanimeapi.py", line 97, in get_episodes_link
    dow_url6 = soup.findAll('div', {'class': 'dowload'})[5].find('a')
IndexError: list index out of range
`
I hope you reply with something when you get free
(Sorry if this is improper, this is my first ever issue I've posted)

Edit: Last night this error appeared after Episode 2 today it's showing this error after Episode 16

**Comment by BaraniARR** [comment]
Some episodes will not have All the Quality, Here this Anime may not have (HDP-mp4) Quality. The best way to get rid of this by iterating all the links and getting those links individually by Index numbers. That's the best way. Anyway, Thank you for reporting.
