### ISSUE TITLE
get_episodes_link error??

### ISSUE THREAD

**Issue by vichubenzene** [BaraniARR/gogoanimeapi#8]
get_episodes_link  is it working correctly now ???... It worked before 2 days... but now i cant get the output

Traceback (most recent call last):
  File "C:/Users/91709/PycharmProjects/pythonProject4/main.py", line 14, in <module>
    anime_link = anime.get_episodes_link(animeid="tonikaku-kawaii-dub", episode_num=3)
  File "C:\Users\91709\PycharmProjects\pythonProject4\venv\lib\site-packages\gogoanimeapi.py", line 92, in get_episodes_link
    dow_url1 = soup.findAll('div', {'class': 'dowload'})[0].find('a')

**Comment by CustomIcon** [comment]
@vichubenzene it has been known they added captcha and only logged in users to see download links

**Comment by vichubenzene** [comment]
1.Is it paid to get a login?
2.where should i login to use this?

**Comment by CustomIcon** [comment]
> 1.Is it paid to get a login? 2.where should i login to use this?
> […](#)
> On Sun, Jun 27, 2021 at 1:27 AM ポキ ***@***.***> wrote: @vichubenzene <https://github.com/vichubenzene> it has been known they added captcha and only logged in users to see download links — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub <[#8 (comment)](https://github.com/BaraniARR/gogoanimeapi/issues/8#issuecomment-869054242)>, or unsubscribe .

gogoanime.io see for yourself. you need to login to get download links but! this package is currently outdated. im hoping dev would fix this or i could open a pr when i find a fix

**Comment by itspranavajay** [comment]
😅

**Comment by itspranavajay** [comment]
> > 1.Is it paid to get a login? 2.where should i login to use this?
> > […](#)
> > On Sun, Jun 27, 2021 at 1:27 AM ポキ _**@**_.***> wrote: @vichubenzene https://github.com/vichubenzene it has been known they added captcha and only logged in users to see download links — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub <[#8 (comment)](https://github.com/BaraniARR/gogoanimeapi/issues/8#issuecomment-869054242)>, or unsubscribe .
> 
> gogoanime.io see for yourself. you need to login to get download links but! this package is currently outdated. im hoping dev would fix this or i could open a pr when i find a fix

Owner is not active, their exam is going on if you want to talk to the owner, join this group on telegram @cosmicaurasupport

**Comment by itspranavajay** [comment]
> > 1.Is it paid to get a login? 2.where should i login to use this?
> > […](#)
> > On Sun, Jun 27, 2021 at 1:27 AM ポキ _**@**_.***> wrote: @vichubenzene https://github.com/vichubenzene it has been known they added captcha and only logged in users to see download links — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub <[#8 (comment)](https://github.com/BaraniARR/gogoanimeapi/issues/8#issuecomment-869054242)>, or unsubscribe .
> 
> gogoanime.io see for yourself. you need to login to get download links but! this package is currently outdated. im hoping dev would fix this or i could open a pr when i find a fix

Already fixed by owner but not active yet

**Comment by sworddefence** [comment]
when will it be active?

**Comment by CosmicPredator** [comment]
Hey there @sworddefence, I fixed that, but due to the exams, I cant implement that. I will update the api as soon as possible. Don't worry.
